### ISSUE TITLE
Add a normalization option

### ISSUE THREAD

**Issue by rmjarvis** [rmjarvis/Piff#113]
Right now our PSF models are all normalized to have unit integral.

@erykoff has explained that this isn't the right thing if you expect to get accurate photometry at the end.  Here is the procedure he laid out for doing the aperture correction:

1. Take a model
2. Apply it to all the stars on a ccd
3. Measure the psf flux with the “unnormalized” psf
4. Measure the aperture flux in the reference aperture
5. normalization is the median/mean/clipped mean/favorite statistic of the the ratio between the unnormalized psf flux and reference aperture flux

My proposal is to do this at the very end of the fitting process of an exposure on all the stars used for fitting.  This will set an overall normalization number for that exposure, which can be saved at the PSF level and applied when drawing the PSF using the final model.

This seems independent of any particular PSF type, so I think this can be a top-level field, which could look like this in the config:
```
normalization:
    type: Aperture
    diameter: 22.22   # radius also allowed
    units: pixels   # arcsec also allowed
```
@beckermr @esheldon @brianyanny
