### ISSUE TITLE
Strange PSF fitting

### ISSUE THREAD

**Issue by drasty03** [rmjarvis/Piff#158]
Hi! I'm trying to use PIFF to model the psf of  a large FOV images. The images are from a QHY411 and have 14200x10650 pixels, I'm cropping the image to half of the image in order to speed up the process. The pixels scale is 0.22 and the catalog that I'm using is only with the detected stars which are 50 times above the sky value (13 stars).

Here is the config file that I'm using (changing between mean and Basispolunomial for interp):
```
input:
    image_file_name: /lab/amadrigal/crop_303413.fits
    cat_file_name: /lab/amadrigal/cat.fits
    x_col: x
    y_col: y
select:
    # Specifying a seed makes the choice of reserve stars deterministic.  
    # Typically set on the command line, since you'd want this to be different for each image.
    seed: 1234   
        
    # Remove >3 sigma outlier in the HSM-measured size.
    # HSM (Hirata, Seljak and Mandelbaum) is an adaptive moment algorithm for measuring size and shapes, 
    # which is pretty stable and is included with GalSim.
    hsm_size_reject: 3   
    min_snr: 50
psf:
    model:
        type: PixelGrid
        scale: 0.30
        size: 17
    interp:
        type: BasisPolynomial
        order: 3
    outliers:
        type: Chisq
        nsigma: 5.5
output:
    file_name: piff_solution.piff
```

I don't understand the result. When I put mean in the interp, the result is near to be normal (see pic 1). But when I change to basispolynomial the result is a rotated square (see pic 2). 

[psf_interp_mean.pdf](https://github.com/rmjarvis/Piff/files/12098994/psf_interp_mean.pdf)
[psf_interp_BasisP.pdf](https://github.com/rmjarvis/Piff/files/12098995/psf_interp_BasisP.pdf)

In both cases, there is a square pattern. I know I'm something wrong but I don't know what. Maybe the solution could be add a weight map but, how to generate it?

Thanks a lot for your work!
