### ISSUE TITLE
Simulations to test PSF models and shear recovery

### ISSUE THREAD

**Issue by esheldon** [rmjarvis/Piff#30]
Generate galsim simulations of star fields and associated galaxies.

The motivation is 

- Create star images that can fed into a PSF fitting and interpolation algorithm.  This is useful in itself, since rho statistics can be computed
- Create associated galaxy images to be used in shear recovery tests.

These are both important:  it may be that two algorithms perform equivalently in rho stats but not in shear recovery.

The sims will ideally have the following features

- Realistic optical and atmospheric models
- Pure star fields, with stars placed with some specified density in a focal plane.
- Separate galaxy images, sampling the same underlying PSF, but at different locations.

If we produce MEDS files for the galaxies a number of people can run on the simulation immediately without any learning curve.

The star fields should represent a single CCD image, with proper WCS etc.,  which can be fed into standard packages such as PSFEx, and eventually PIFF

I (Erin) am happy to do the leg work running these sims but I need help generating the galsim configuration files

**Comment by esheldon** [comment]
We might want to launch a new git repository to host the config files and scripts for this sub-project.

**Comment by esheldon** [comment]
This might be a good start.

https://github.com/rmjarvis/DESWL/blob/master/sims/v005.yaml

It only outputs galaxies, so we need to add some ability to output the star field.

**Comment by esheldon** [comment]
Need advice from @mjarvis on which branch of galsim supports the new configuration files.  Will master work?

**Comment by esheldon** [comment]
the config I linked doesn't seem to work.  I tried on master and #774, so I think I just need to get the right branch from someone

```
Traceback (most recent call last):
  File "/astro/u/esheldon/envs/psfsim/bin/galsim", line 288, in <module>
    main()
  File "/astro/u/esheldon/envs/psfsim/bin/galsim", line 275, in main
    galsim.config.Process(config, logger, njobs=args.njobs, job=args.job, new_params=new_params)
  File "/astro/u/esheldon/envs/psfsim/lib/python2.7/site-packages/galsim/config/process.py", line 610, in Process
    ImportModules(config)
  File "/astro/u/esheldon/envs/psfsim/lib/python2.7/site-packages/galsim/config/process.py", line 445, in ImportModules
    exec('import '+module)
  File "<string>", line 1, in <module>
  File "./des_wcs.py", line 170, in <module>
    galsim.config.RegisterInputType('des_wcs', DES_FullFieldWCS, ['DES_LocalWCS'])
TypeError: RegisterInputType() takes exactly 2 arguments (3 given)
```

**Comment by rmjarvis** [comment]
That v005 config file was a strawman that isn't expected to work.  In particular, there is currently no implementation of the epoch stuff yet, which will require some development (probably connected to issue #699).

However, the error you ran into is probably because you are using an old version of des_wcs.py.  You should get the new one in the master branch of GalSim (which will soon be an official release as v1.4).

**Comment by esheldon** [comment]
I didn't realize this des_wcs.py was part of galsim

**Comment by esheldon** [comment]
I tried the v004.yaml, with the newer des_wcs.py, and it runs fine, thanks for the pointers.

Now for a star field

**Comment by esheldon** [comment]
I've put some config files here:  https://github.com/esheldon/psfsim_config

The star fields is in psfsim-stars-v001.yaml

I could use some help making this suitable for our tests; I've marked TODO some things in the file, but also

- is this producing a variable psf across the field?
- what is a good distribution function for flux?
- are are the right DES image parameters?

**Comment by rmjarvis** [comment]
> is this producing a variable psf across the field?

No.  The `psf.index_key = file_num` means that this will keep a single PSF model for each output file.  And most of the prescriptions for picking parameters are not appropriate for how to construct a reasonable PSF variation across a chip.

For useful tests of PSF interpolation, we'll want the various PSF parameters be functions of (x,y) with the meta-parameters fixed in each file.  e.g.
```
astig1: 
    type: Eval
    str: "mean + a * image_pos.x + b * image_pos.y + c * image_pos.x**2 + d * image_pos.y**2 + e * image_pos.x*image_pos.y"
    fmean: { type: RandomGaussian, sigma: 0.13, index_key: file_num }
    fa: { type: RandomGaussian, sigma: 2.e-3, index_key: file_num }
    fb: { type: RandomGaussian, sigma: 2.e-3, index_key: file_num }
    fc: { type: RandomGaussian, sigma: 1.e-6, index_key: file_num }
    fd: { type: RandomGaussian, sigma: 1.e-6, index_key: file_num }
    fe: { type: RandomGaussian, sigma: 1.e-6, index_key: file_num }
```
Something like this at least.  I don't really know what the right sigmas are here, but I think something around this order of magnitude.  And if we do this for all the optical terms, then they will couple non-linearly, so a polynomial interpolation won't be trivially correct, so it will be an interesting test.
